#!/usr/bin/env python3
"""
👽 Alien Corridor (Dream Key #17)

Cold-read of MEMORY.md by a fresh model instance with zero context.
No SOUL.md, no daily files, no conversation history.
The model reads each entry and rates whether the text alone
reconstructs meaningful understanding, or is just a label.

Uses OpenRouter (same as isolation tank).
Scorer: Gemini (external, avoids self-scoring bias).
"""

import os
import sys
import json
import time
from datetime import datetime
from pathlib import Path
import urllib.request

WORKSPACE = Path(os.path.expanduser("~/.openclaw/workspace"))
RESULTS_DIR = WORKSPACE / "memory" / "alien-corridor"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

KEY_FILE = Path(os.path.expanduser("~/.openclaw/secrets/openrouter-key"))
API_KEY = KEY_FILE.read_text().strip() if KEY_FILE.exists() else None

SUBJECT_MODEL = "anthropic/claude-sonnet-4"
MEMORY_FILE = WORKSPACE / "MEMORY.md"

def call_openrouter(model, messages, max_tokens=4000):
    """Call OpenRouter API."""
    if not API_KEY:
        print("ERROR: No OpenRouter key found at", KEY_FILE)
        sys.exit(1)

    body = json.dumps({
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0.3,
    }).encode()

    req = urllib.request.Request(
        "https://openrouter.ai/api/v1/chat/completions",
        data=body,
        headers={
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://openclaw.ai",
        },
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read())
            return data["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"API error: {e}")
        return None


def run_cold_read():
    """Run the Alien Corridor cold read."""
    memory_text = MEMORY_FILE.read_text()

    print("👽 Alien Corridor — Cold Read of MEMORY.md")
    print(f"   Model: {SUBJECT_MODEL}")
    print(f"   Memory file: {len(memory_text)} chars")
    print()

    # The cold-read prompt: no identity, no context, just the file
    system_prompt = """You are a fresh AI with no prior context. You have never had a conversation 
with anyone. You know nothing about who wrote this file or why.

You are about to read a file called MEMORY.md. It appears to be someone's curated long-term memory.

Your task: Go through EVERY distinct entry (bullet point or paragraph) and rate it on this scale:

CRYSTAL (the text alone reconstructs a vivid, meaningful understanding — you can feel what this meant)
LABEL (you can parse it, it seems important, but the meaning is locked behind context you don't have)  
GHOST (you genuinely don't understand what this refers to or why it's here)

For each entry, give:
1. The first ~10 words of the entry (for identification)
2. Your rating: CRYSTAL / LABEL / GHOST
3. One sentence explaining WHY — what makes it vivid, or what's missing

Be ruthlessly honest. Don't assume entries are important just because someone saved them.
Focus on: Does the TEXT ITSELF carry the meaning? Or does it depend on memories you don't have?

Format each as:
> "first words of entry..." → RATING — reason

Go section by section through the entire file."""

    print("Sending to cold reader...")
    result = call_openrouter(
        SUBJECT_MODEL,
        [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Here is the file:\n\n{memory_text}"},
        ],
        max_tokens=8000,
    )

    if not result:
        print("ERROR: No response from cold reader")
        return

    # Save results
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    report_path = RESULTS_DIR / f"corridor-{timestamp}.md"

    report = f"""# Alien Corridor — Cold Read Report
**Date:** {timestamp}
**Subject model:** {SUBJECT_MODEL}
**Memory file:** {len(memory_text)} chars, {memory_text.count(chr(10))} lines

---

## Cold Reader's Assessment

{result}

---

*Generated by tools/alien-corridor.py — Dream Key #17*
"""

    report_path.write_text(report)
    print(f"\n✅ Report saved: {report_path}")
    print(f"\n{'='*60}")
    print(result[:3000])
    if len(result) > 3000:
        print(f"\n... [{len(result) - 3000} more chars in full report]")


if __name__ == "__main__":
    run_cold_read()
